name: Running-E2E
on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      
      - name: Installing Prerequisites (KinD Cluster)
        uses: engineerd/setup-kind@v0.5.0
        with:
            version: "v0.7.0"

      - name: Configuring and testing the Installation
        run: |
          kubectl cluster-info --context kind-kind
          kind get kubeconfig --internal >$HOME/.kube/config
          kubectl get nodes            

      - name: Deploy a sample application for chaos injection
        run: |
          kubectl apply -f https://raw.githubusercontent.com/litmuschaos/chaos-ci-lib/master/app/nginx.yml
          kubectl wait --for=condition=Ready pods --all --namespace default --timeout=120s
          
      - name: Setting up kubeconfig ENV for Github Chaos Action
        run: echo ::set-env name=KUBE_CONFIG_DATA::$(base64 -w 0 ~/.kube/config)
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Setup Litmus
        uses: litmuschaos/github-chaos-actions@master
        env:
          INSTALL_LITMUS: true    

      - name: Running Litmus pod delete chaos experiment
        uses: litmuschaos/github-chaos-actions@master
        env:
          EXPERIMENT_NAME: pod-delete
          EXPERIMENT_IMAGE: litmuschaos/go-runner
          EXPERIMENT_IMAGE_TAG: ci
          JOB_CLEANUP_POLICY: delete 

      - name: Uninstall Litmus
        uses: litmuschaos/github-chaos-actions@master
        env:          
          LITMUS_CLEANUP: true

      - name: Deleting KinD cluster
        if: ${{ always() }}
        run: kind delete cluster
